<?php
// Get local settings for Divido
$product     = Mage::registry('product');
$priceincvat = Mage::helper('tax')->getPrice($product, $product->getPrice());
$isActive    = Mage::helper('pay')->isActiveLocal($product);

if ($isActive) {
    $plans    = Mage::helper('pay')->getLocalPlans($product);
    $planList = Mage::helper('pay')->plans2list($plans);
}

$showCalc = $isActive && $plans;
?>

<?php if ($showCalc): ?>
<div class="divido-widget">
    <div data-divido-widget data-divido-plans="<?php echo $planList; ?>" data-divido-amount="<?php echo $priceincvat; ?>"></div>
</div>
<?php endif; ?>
