<?php
// Get local settings for Divido
$product  = Mage::registry('product');
$isActive = Mage::helper('pay')->isActiveLocal($product);

if ($isActive) {
    $plans    = Mage::helper('pay')->getLocalPlans($product);
    $planList = Mage::helper('pay')->plans2list($plans);
}

$showCalc = $isActive && $plans;
?>
<div class="divido-widget">
    <div data-divido-widget data-divido-plans="<?php echo $planList; ?>" data-divido-amount="<?php echo $product['price']; ?>"></div>
</div>
