<?php
// Get local settings for Divido
$product     = Mage::registry('product');
$priceincvat = Mage::helper('tax')->getPrice($product, $product->getPrice());
$isActive    = Mage::helper('pay')->isActiveLocal($product);

if ($isActive) {
    $plans    = Mage::helper('pay')->getLocalPlans($product);
    $planList = Mage::helper('pay')->plans2list($plans);
}

$showCalc = $isActive && $plans;
?>
<script>
window.__DIVIDO_SHOW_CALC = <?php echo $showCalc ? 'true' : 'false'; ?>;

jQuery(document).ready(function($) {
    if (! window.__DIVIDO_SHOW_CALC) {
        var tabIndex = jQuery('#divido-container').parent().parent().index('dd');
        jQuery('.product-collateral ul.toggle-tabs li').eq(tabIndex).hide();
    }
});

</script>

<div id="divido-container">
    <?php if ($showCalc): ?>
    <div class="divido-calculator divido-theme-blue" data-divido-calculator data-divido-plans="<?php echo $planList; ?>" data-divido-amount="<?php echo $priceincvat; ?>">
        
        <h1>
            <a href="https://www.divido.com" target="_blank" class="divido-logo divido-logo-sm" style="float:right;">Divido</a>
            Pay in instalments
        </h1>
                
        <dl>
          <dt><span data-divido-choose-finance data-divido-label="Choose your plan" data-divido-form="finance"></span></dt>
          <dd><span class="divido-deposit" data-divido-choose-deposit data-divido-label="Choose your deposit" data-divido-form="deposit"></span></dd>
        </dl>
        
        <div class="description"><strong><span data-divido-agreement-duration></span> monthly payments of <span data-divido-monthly-instalment></span></strong></div>
                
        <div class="divido-info">

            <dl>
              <dt>Term</dt>
              <dd><span data-divido-agreement-duration></span> months</dd>
              <dt>Monthly instalment</dt>
              <dd><span data-divido-monthly-instalment></span></dd>
              <dt>Deposit</dt>
              <dd><span data-divido-deposit></span></dd>
              <dt>Cost of credit</dt>
              <dd><span data-divido-finance-cost-rounded></span></dd>
              <dt>Total payable</dt>
              <dd><span data-divido-total-payable-rounded></span></dd>
              <dt>Total interest APR</dt>
              <dd><span data-divido-interest-rate></span></dd>
            </dl>
        </div>
        
        <div class="clear"></div>

    </div>
    <?php endif; ?>
</div>
