<?php 
$_code      = $this->getMethodCode();

$plans      = Mage::helper('pay')->getGlobalSelectedPlans();
$planList   = Mage::helper('pay')->plans2list($plans);
$grandTotal = Mage::getSingleton('checkout/cart')->getQuote()->getGrandTotal();
?>
<script>
jQuery(document).ready(function($) {
	divido_calculator($("#divido-checkout"));
});
</script>

<div id="payment_form_<?php echo $_code ?>" style="display:none;">
    <fieldset id="divido-checkout" class="divido-calculator divido-theme-blue" data-divido-amount="<?php echo $grandTotal; ?>" data-divido-plans="<?php echo $planList; ?>">
        <h1>
            <a href="https://www.divido.com" target="_blank" class="divido-logo divido-logo-sm" style="float:right;">Divido</a>
            Pay in instalments
        </h1>
        <div style="clear:both;"></div>
        <dl>
            <dt><span data-divido-choose-finance data-divido-label="Choose your plan" data-divido-form="divido_finance"></span></dt>
            <dd><span class="divido-deposit" data-divido-choose-deposit data-divido-label="Choose your deposit" data-divido-form="divido_deposit"></span></dd>
        </dl>
        <div class="description">
            <strong>
                <span data-divido-agreement-duration></span> monthly payments of <span data-divido-monthly-instalment></span>
            </strong>
        </div>
        <div class="divido-info">
            <dl>
                <dt>Term</dt>
                <dd><span data-divido-agreement-duration></span> months</dd>
                <dt>Monthly instalment</dt>
                <dd><span data-divido-monthly-instalment></span></dd>
                <dt>Deposit</dt>
                <dd><span data-divido-deposit></span></dd>
                <dt>Amount of credit</dt>
                <dd><span data-divido-credit-amount></span></dd>
                <dt>Total payable</dt>
                <dd><span data-divido-total-payable></span></dd>
                <dt>Total interest APR</dt>
                <dd><span data-divido-interest-rate></span></dd>
            </dl>
        </div>
        <div class="clear"></div>
        <p>You will be redirected to Divido to complete this finance application when you place your order</p>
    </fieldset>
</div>
